---
- name: get oracle installer
  get_url:
    url: "{{ oracle_installer_uri }}/{{ installer }}"
    dest: "{{ oracle_tmp }}/{{ installer }}"

- name: verify installer checksum
  command: cksum {{ oracle_tmp }}/{{ installer }}
  register: installer_check
  failed_when: "installer_check.stdout.find('{{ checksum }}') != 0"

- name: unzip installer
  shell: unzip -o -d {{oracle_tmp}} {{oracle_tmp}}/{{installer}}
